# Generated by Django 6.0.6 on 2026-06-22 09:33

import members.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_address_member_age_member_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, validators=[members.validators.validate_contact_number]),
        ),
    ]
